#!/usr/bin/env bash
# pings an IP address passed as an argument
if [ $# -eq 0 ]; then # $# is the number of arguments passed to the script.
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1" # first argument is the IP, send 5 ping packets then stop